# Name of workflow
name: NodeCI

# Trigger the workflow on push
on: [push, pull_request]

env:
  CI: true

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest
    # Node versions list
    strategy:
      matrix:
        node-version: [16.x]

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      - run: make install
      - run: make build
      - run: make lint